### ISSUE TITLE
Multiple GPU compatibility is broken with Pytorch 1.6

### ISSUE THREAD

**Issue by AtlantixJJ** [DiffEqML/torchdyn#41]
Just as I upgrade to pytorch 1.6, original torchdyn code cannot run under multiple GPUs. The error is as following:

```
Traceback (most recent call last):
  File "manipulation/ffjord.py", line 116, in <module>
    trainer.fit(learn, train_dl)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/trainer/trainer.py", line 1016, in fit
    results = self.accelerator_backend.train()
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/accelerators/dp_backend.py", line 99, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/trainer/trainer.py", line 1237, in run_pretrain_routine
    self.train()
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/trainer/training_loop.py", line 396, in train
    self.run_training_epoch()
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/trainer/training_loop.py", line 484, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/trainer/training_loop.py", line 838, in run_training_batch
    self.hiddens
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/trainer/training_loop.py", line 1005, in optimizer_closure
    training_step_output = self.accelerator_backend.training_step(args)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/accelerators/dp_backend.py", line 111, in training_step
    output = self.trainer.model(*args)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/overrides/data_parallel.py", line 83, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/overrides/data_parallel.py", line 147, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/overrides/data_parallel.py", line 288, in parallel_apply
    raise output
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/pytorch_lightning-0.9.1rc1-py3.7.egg/pytorch_lightning/overrides/data_parallel.py", line 245, in _worker
    output = module.training_step(*input, **kwargs)
  File "manipulation/ffjord.py", line 74, in training_step
    trJ_z = self.forward(x)
  File "manipulation/ffjord.py", line 61, in forward
    return self.model(self.augmenter(x.view(x.shape[0], -1)))
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./torchdyn/models/neuralde.py", line 81, in forward
    out = odeint(x)
  File "./torchdyn/models/neuralde.py", line 115, in _adjoint
    return self.adjoint(self.defunc, x, self.s_span, rtol=self.rtol, atol=self.atol, method=self.solver)
  File "/home/b146466/anaconda3/envs/xjj/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./torchdyn/sensitivity/adjoint.py", line 93, in forward
    self.flat_params = flatten(func.parameters()) ; self.s_span = s_span
  File "./torchdyn/sensitivity/adjoint.py", line 23, in flatten
    return torch.cat([el.contiguous().flatten() for el in iterable])
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, Autograd, Profiler, Tracer, Autocast]
```

The compatibility problem is also present in torchdiffeq and just got fixed (https://github.com/rtqichen/torchdiffeq/issues/119). I think you probably have the same issue as torchdiffeq. Hope it helps.

**Comment by Zymrael** [comment]
Thank you for pointing out the issue. The problem is indeed related to torchdiffeq's. We put together a quick fix, could you check if the following runs after cloning the latest version of `torchdyn`?

```
f = nn.Sequential(
        nn.Linear(2, 4),
        nn.Tanh(), 
        nn.Linear(4, 2))
model = NeuralDE(f, sensitivity='adjoint', solver='dopri5')

x = torch.randn(10, 2, requires_grad=True)
data_p = nn.DataParallel(model, (0,))
x_in = torch.autograd.Variable(x, requires_grad=True)
out = data_p(Xin)
torch.autograd.grad(out.sum(), x_in , create_graph=True)
```

**Comment by Zymrael** [comment]
`DataParallel` works with the new version.
