### ISSUE TITLE
Dopri5 solver does not respect s_span

### ISSUE THREAD

**Issue by Mikkolehtimaki** [DiffEqML/torchdyn#63]
I'm working on sequential MNIST with an RNN and using DepthCat to have access to time of the ODE. I set `s_span = torch.linspace(0, 27, 28)` for [0, 27] time interval. However, when extracting t from the state in forward(), I get t values greater than 27. This does not happen with the rk4 solver so is the time interval enforced properly? Here's logs:

```
Printing modules
[Neural DE:
	- order: 1        
	- solver: dopri5
	- integration interval: 0.0 to 27.0        
	- num_checkpoints: 28        
	- tolerances: relative 0.0001 absolute 0.0001        
	- num_parameters: 128        
	- NFE: 0.0
        
Traceback (most recent call last):
  File "pixel_mnist_rnn.py", line 181, in main
    rnn, lossfun, test_loader, device=DEVICE, repeats=num_repeats)
  File "/mypath/data/workdir/data_utils.py", line 137, in test
    out = model(x)
  File "/mypath/envs/neuralodes/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _cal
l_impl
    result = self.forward(*input, **kwargs)
  File "pixel_mnist_rnn.py", line 116, in forward
    x = self.ode(init)
  File "/mypath/envs/neuralodes/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _cal
l_impl
    result = self.forward(*input, **kwargs)
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdyn/models/neuralde.py", line 81, in forwar
d
    out = odeint(x)
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdyn/models/neuralde.py", line 109, in _auto
grad
    atol=self.atol, method=self.solver)[-1]
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdiffeq/_impl/odeint.py", line 75, in odeint
    solution = solver.integrate(t)
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdiffeq/_impl/solvers.py", line 30, in integ
rate
    solution[i] = self._advance(t[i])
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdiffeq/_impl/rk_common.py", line 194, in _a
dvance
    self.rk_state = self._adaptive_step(self.rk_state)
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdiffeq/_impl/rk_common.py", line 255, in _a
daptive_step
    y1, f1, y1_error, k = _runge_kutta_step(self.func, y0, f0, t0, dt, t1, tableau=self.tableau)
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdiffeq/_impl/rk_common.py", line 76, in _ru
nge_kutta_step
    f = func(ti, yi, perturb=perturb)
  File "/mypath/envs/neuralodes/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _cal
l_impl
    result = self.forward(*input, **kwargs)
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdiffeq/_impl/misc.py", line 191, in forward
    return self.base_func(t, y)
  File "/mypath/envs/neuralodes/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _cal
l_impl
    result = self.forward(*input, **kwargs)
  File "/mypath/envs/neuralodes/lib/python3.6/site-packages/torchdyn/models/defunc.py", line 51, in forward
    else: x = self.m(x)
  File "/mypath/envs/neuralodes/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _cal
l_impl
    result = self.forward(*input, **kwargs)
  File "/mypath/envs/neuralodes/lib64/python3.6/site-packages/torch/nn/modules/container.py", line 117, in f
orward
    input = module(input)
  File "/mypath/envs/neuralodes/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _cal
l_impl
    result = self.forward(*input, **kwargs)
  File "pixel_mnist_rnn.py", line 71, in forward
    pixels = self.data[torch.arange(x.shape[0]), t.long().squeeze(), :]
IndexError: index 28 is out of bounds for dimension 1 with size 28

```

**Comment by Zymrael** [comment]
This is related to the way[`torchdiffeq` does interpolation with `dopri5`](https://github.com/rtqichen/torchdiffeq/issues/78). In short, do not worry about seeing those larger values since those will not be part of your output (solution).

**Comment by Mikkolehtimaki** [comment]
Okay, thank you. I do need to implement some checking though, since I'm using time to index into my input tensor, so it is a bit clumsy.

**Comment by Zymrael** [comment]
Closing as we now have our internal version of `dopri5`
